---
require: rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: disable
  DisabledByDefault: false
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'