---
version: "3"

services:
# --[application]--------------------------------------------------------------
  rails_base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV}
    depends_on:
      - postgres_db
      - redis_db
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SWAGGER_HOST=${SWAGGER_HOST}
    env_file:
      - ./envs/postgres.env
    ports:
      - 80:3000
    volumes:
      - .:/rails_base

# --[dependencies]-------------------------------------------------------------
  postgres_db:
    image: postgres:12.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./envs/postgres.env

  redis_db:
    image: redis:7.0.11
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  
  